# Generated by Django 6.0.6 on 2026-07-01 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('icon', models.CharField(blank=True, help_text='FontAwesome class e.g. fa-shirt', max_length=100)),
                ('theme', models.CharField(blank=True, help_text='Theme class e.g. men-theme', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.SlugField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('card_description', models.TextField(help_text='Short description for the service cards')),
                ('detailed_description', models.TextField(help_text='Detailed description for the service tabs')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('icon_color_class', models.CharField(blank=True, max_length=50)),
                ('icon_svg', models.TextField(blank=True, help_text='Raw SVG code for the icon')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('clean_iron_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('steam_iron_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier e.g. shirt', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='items/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='website.itempricecategory')),
            ],
        ),
    ]
