# Generated by Django 6.0.6 on 2026-07-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemprice',
            name='category',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='ItemPrice',
        ),
        migrations.DeleteModel(
            name='ItemPriceCategory',
        ),
    ]
