# Generated by Django 6.0.6 on 2026-07-01 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['priority', 'id']},
        ),
        migrations.AddField(
            model_name='module',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
