# Generated by Django 6.0.6 on 2026-07-01 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_module_options_module_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='vehicle_make',
        ),
        migrations.RemoveField(
            model_name='serviceenquiry',
            name='vehicle_model',
        ),
    ]
