# Generated by Django 6.0.6 on 2026-07-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_remove_serviceenquiry_vehicle_make_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='featured_image',
            field=models.ImageField(upload_to='blog/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='meta_tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags (e.g., Laundry Care, Dry cleaning Tips)', max_length=255, null=True),
        ),
    ]
