# Generated by Django 5.2.14 on 2026-07-03 10:16

from django.db import migrations


def seed_pages(apps, schema_editor):
    Page = apps.get_model('dashboard', 'Page')
    
    default_pages = [
        {"title": "Home", "slug": "home", "priority": 1},
        {"title": "About Us", "slug": "about", "priority": 2},
        {"title": "Services", "slug": "service", "priority": 3},
        {"title": "Booking", "slug": "booking", "priority": 4},
        {"title": "Contact", "slug": "contact", "priority": 5},
        {"title": "Location", "slug": "location", "priority": 6},
    ]
    
    for pd in default_pages:
        Page.objects.get_or_create(slug=pd['slug'], defaults={
            'title': pd['title'],
            'priority': pd['priority'],
            'show_in_menu': True
        })

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_companydetails_alter_blog_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_pages, reverse_seed),
    ]
