# Generated by Django 5.2.14 on 2026-07-03 10:43

from django.db import migrations


def seed_pages(apps, schema_editor):
    Page = apps.get_model('dashboard', 'Page')
    
    default_pages = [
        {"title": "Home", "page_name": "Home", "slug": "home", "priority": 1, "position": "header"},
        {"title": "About Us", "page_name": "About Us", "slug": "about", "priority": 2, "position": "header"},
        {"title": "Services", "page_name": "Services", "slug": "service", "priority": 3, "position": "header"},
        {"title": "Booking", "page_name": "Booking", "slug": "booking", "priority": 4, "position": "header"},
        {"title": "Location", "page_name": "Location", "slug": "location", "priority": 5, "position": "header"},
        {"title": "Contact", "page_name": "Contact", "slug": "contact", "priority": 6, "position": "header"},
        {"title": "Creek Harbour", "page_name": "Creek Harbour", "slug": "location-creek-harbour", "priority": 7, "position": "header"},
        {"title": "Business Bay", "page_name": "Business Bay", "slug": "location-business-bay", "priority": 8, "position": "header"},
        {"title": "Down Town", "page_name": "Down Town", "slug": "location-down-town", "priority": 9, "position": "header"},
    ]
    
    for pd in default_pages:
        obj, created = Page.objects.get_or_create(slug=pd['slug'], defaults={
            'title': pd['title'],
            'page_name': pd['page_name'],
            'priority': pd['priority'],
            'position': pd['position'],
            'show_in_menu': True
        })
        if not created:
            obj.position = pd['position']
            obj.page_name = pd['page_name']
            obj.save()

def reverse_seed(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_seed_default_pages'),
    ]

    operations = [
        migrations.RunPython(seed_pages, reverse_seed),
    ]
