# Generated by Django 5.2.14 on 2026-07-04 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_update_seed_pages'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('service_speed', models.CharField(default='standard', max_length=50)),
                ('pickup_address', models.TextField()),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Booking Enquiries',
                'db_table': 'dash_bookingenquiry',
            },
        ),
        migrations.DeleteModel(
            name='ServiceEnquiry',
        ),
    ]
