# Generated by Django 6.0.6 on 2026-07-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_blog_id_alter_bookingenquiry_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydetails',
            name='email_logo_url',
            field=models.URLField(blank=True, help_text='Upload a hosted link from Google Drive or any image host to guarantee your logo appears in emails.', max_length=500, null=True),
        ),
    ]
