# Generated by Django 6.0.6 on 2026-07-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_companydetails_email_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydetails',
            name='email_logo_url',
            field=models.CharField(blank=True, help_text='Google Drive Logo ID: Extract and paste ONLY the file ID from your Google Drive share link.', max_length=500, null=True),
        ),
    ]
